site_name: SiteName
site_url: https://gfrovera.github.io/resume-profile-docs/
site_author: Garrett Rovera

nav:
    - Home: index.md
    # - Projects: 

theme:
    name: material

# plugins:
#   - search


# markdown_extensions:
#   - pymdownx.tabbed
#   - pymdownx.highlight
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences
