site_name: SiteName
site_url: https://gfrovera.github.io/resume-profile-docs/
site_author: Garrett Rovera
nav:
  - Home: index.md
  # - Projects:
  #   - DadBot: dadbot/overview.md
theme:
  name: material
  features:
    - navigation.tabls
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en


# plugins:
#   - search


# markdown_extensions:
#   - pymdownx.tabbed
#   - pymdownx.highlight
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences
